#!/usr/bin/env bash
# If the first argument is an youtube url, converts it to yewtu.be and opens it
# with qutebrowser

URL=$1

#if [[ $URL =~ youtu ]]; then
#    URL="https://yewtu.be/${URL##*/}"
#fi

#qutebrowser $URL
chromium --user-data-dir=$HOME/.config/chromium-app  --class=Any \
    --new-window --enable-features=WebUIDarkMode --force-dark-mode \
    --incognito --app=$URL
